#!/bin/bash
#
# xmonad "startup hook" script. This gets run after xmonad is initialized,
# via the startupHook facility provided by xmonad. It's useful for
# running any programs which you want to use within xmonad but
# which don't need to be initialized before xmonad is running.
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

# Use synapse as our app launcher. (-s: don't display until requested)
if [ -z "$(pgrep synapse)" ] ; then
  synapse -s &
fi

#
# TRAY ICON SOFTWARE
#

# Empathy chat client (-h: start hidden, -n: don't connect on launch)
if [ -z "$(pgrep empathy)" ] ; then
  empathy -h -n &
fi

# Remmina remote desktop connection client (-i: start hidden)
if [ -z "$(pgrep remmina)" ] ; then
  remmina -i &
fi

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
  nm-applet --sm-disable &
fi

# Applet for managing print jobs from the tray.
if [ -z "$(pgrep system-config-printer-applet)" ] ; then
  system-config-printer-applet &
fi

#
# APPLICATION LAUNCHER
#

# keybase
if [-z "$(pgrep run_keybase)"]; then
  run_keybase &
fi

# guake
if [-z "$(pgrep guake)"]; then
  guake &
fi


# start flux
$HOME/.xmonad/bin/start-redshift

## dunst
dunst -conf ~/.xmonad/dunst/dunstrc &

# ssh keys
if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-thing
fi
if [[ ! "$SSH_AUTH_SOCK" ]]; then
    eval "$(<~/.ssh-agent-thing)"
fi
ssh-add ~/.ssh/jethrosun_rsa &

# HACK: to fix the weird alacritty pacnic bug
#fcitx &

# get the time zone rolling!
#~/.local/bin/tzupdate

# Manage multi screens and polybar
#sudo -E -u jethros $HOME/.xmonad/bin/hotplug-dp.sh &  # laptop setup
sudo -E -u jethros $HOME/.xmonad/bin/hotplug-dp.sh mirror &  # desktop setup

# HACK
#xrandr | grep 'DP-2 connected' | ifne xrandr --output DP-2 --auto --left-of eDP-1

# On login, we unlock the ssh keychain so we're not prompted for
# passphrases later. We pipe /dev/null to ssh-add to make it realize
# it's not running in a terminal. Otherwise, it won't launch the prompt.
#
# If you don't use the ssh keychain you may not want this. Commented
# by default as it is assumed many users will not want this feature.

# export SSH_ASKPASS="/usr/bin/ssh-askpass"
# cat /dev/null | ssh-add &

# I disable the middle mouse button because otherwise I constantly
# accidentally paste unwanted text in the middle of my code while scrolling.
# Note that the id of the mouse device may be different depending on
# which usb port it is plugged into! To find it, use:
# xinput list |grep 'id='
# In the following command, the id is the first argument, the rest is
# the remapping.

# set mouse
xsetroot -cursor_name left_ptr &

# Commented by default as it is assumed many users will not want this.
#xinput set-button-map 10 1 0 3 4 5 6 7
sudo -E -u jethros $HOME/.xmonad/bin/touchpad-setup.sh &
