#!/bin/bash
#
# xmonad startup script. Intended to be run from an xsession configuration
# to run xmonad and some associated programs.
#
# Author: David Brewer
# Repository: https://github.com/davidbrewer/xmonad-ubuntu-conf

#
# GENERAL INITIALIZATION
#

# Identify the home of our gtkrc file, important for setting styles of
# gtk-based applications
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Load X resources (fixes some font issues)
xrdb -merge .Xresources

# Start compositing to support transparency. You can omit this
# if you prefer not to use any transparency, but it is likely to cause
# ugly black fringing with some programs such as synapse that expect
# transparency support.
xcompmgr -n &

# Here I run some personal little things
#
# Crusial here because only this can make it happen
# -----------------------
guake & 

ssh-add ~/.ssh/cloud.pem & 
ssh-add ~/.ssh/jsun7 & 
ssh-add ~/.ssh/id_rsa &

($HOME/.dropbox-dist/dropboxd &) &
urxvtd & 

# TLP
# https://wiki.archlinux.org/index.php/TLP
tlp start & 

# Kill bluetooth
rfkill block bluetooth

# NOTE(jethro): 
# on screen locking, I find the solution to be xss-lock (after trying all other
# options online). Go to Gnome/Settings/Bright&Lock and turn off screen lock, 
# now only use xss-lock to control the screen lock.
# P.S. It worked perfect with Yubico keychain.
xss-lock -- gnome-screensaver-command --lock &
#xss-lock -- xscreensaver-command -lock &

#
# SCREEN CONFIGURATION
#
# We handle our screen configuration using xrandr. You are likely to want to
# edit this section to match the specific demands of your setup. The below
# setup is for a Lenovo W520 laptop that sometimes has an external monitor
# hooked up via either VGA or DVI, positioned to the left of the laptop.
#
# Note that you can run xrandr at the command line to get a list of your
# connected screens and find out what names you should use to refer to them.

## Activate primary screen

# My primary screen will be the big monitor, o/w my be-trusted thinkpad
xrandr --output eDP-1 --auto --primary   # by default
xrandr | grep 'DP-2 connected' | ifne xrandr --output DP-2 --auto --primary
xrandr | grep 'DP-2 connected' | ifne xrandr --output eDP-1 --auto --left-of DP-2

# If we find that a screen is connected via VGA, activate it and position it
# to the left of the primary screen.
#xrandr | grep 'VGA1 connected' | ifne xrandr --output VGA1 --auto --primary

# If we find that a screen is connected via DVI, activate it and position it
# to the left of the primary screen.
#xrandr | grep 'DP-1 connected' | ifne xrandr --output DP-1 --auto --right eDP-1

# LOAD SCREEN BACKGROUNDS
# To set your backgrounds, run nitrogren /path/to/images
nitrogen --restore &
# This works
#feh --bg-fill ~/Dropbox/wallpapers/bg.jpg   &


#
# STARTUP ICON TRAY
#

# We are using stalonetray to create a small icon tray at the
# top right of the screen. You are likely to want to tweak the
# size of the icons and the width of the tray based upon the
# size of your screen and your xmobar configuration. The goal is
# to make stalonetray look like it is part of xmobar.
#
# Line by line, the options used by default below mean:
# - icons should be aligned with the "East" or right side of the tray
# - the width of the tray should be 5 icons wide by one icon tall, and it
#   should be located 0 pixels from the right of the screen (-0) and 0 pixels
#   from the top of the screen (+0).
# - By setting our maximum geometry to the same thing, the tray will not grow.
# - The background color of the tray should be black.
# - This program should not show up in any taskbar.
# - Icons should be set to size "24".
# - Kludges argument of "force_icons_size" forces all icons to really, truly
#   be the size we set.
# - window-strut "none" means windows are allowed to cover the tray. In
#   other words, trust xmonad to handle this part.
#
#stalonetray \
#  --icon-gravity E \
#  --geometry 5x1-0+0 \
#  --max-geometry 5x1-0+0 \
#  --background '#000000' \
#  --skip-taskbar \
#  --icon-size 24 \
#  --kludges force_icons_size \
#  --window-strut none \
#&

# better start taffybar after the tray
taffybar &

# Run the gnome-keyring-daemon to avoid issues you otherwise may encounter
# when using gnome applications which expect access to the keyring, such
# as Empathy. This prevents prompts you may otherwise get for invalid
# certificates and the like.
gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh

# Remap caps lock to left control. This is not strictly speaking
# xmonad related, but it's handy if you're a vim user.
setxkbmap -option 'ctrl:swapcaps'

slack &
nocturn & 
chromium-browser & 
xsetroot -cursor_name left_ptr & 


# Now, finally, start xmonad
exec xmonad
